name: action-fastapi-heroku-test
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black pytest
          python -m pip install -r requirements.txt

      - name: Deploying to Heroku
        env:
          HEROKU_AUTH_TOKEN : ${{ secrets.HEROKU_AUTH_TOKEN }}
          HEROKU_APP_NAME : ${{ secrets.HEROKU_APP_NAME }}
        if: github.ref == 'ref/heads/main' && job.status == 'success'
        run: |
          git remote add heroku https://heroku:$HEROKU_AUTH_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku main




